version: 1
ghcr:
  upload: true
  cve-scan: false

registries:
  docker.io:
    uri: docker.io/alesancor1
    auth:
      - method: basic
        config:
          username: secrets.DOCKERHUB_USERNAME          # @@@@@@ DO NOT PUT ACTUAL CREDENTIALS HERE @@@@@@
          password: secrets.DOCKERHUB_TOKEN             # @@@@@@ DO NOT PUT ACTUAL CREDENTIALS HERE @@@@@@

images:
  - directory: "*"
  - directory: "my-rock-name/0.1-24.04"
    registries:
      - docker.io
  - directory: "my-rock-name/0.1-22.04"
    pro-services:
      - esm-apps
      - esm-infra