name: Publish Rocks to GHCR

on:
  workflow_run:
    workflows: [Build Rocks]
    branches: [main]
    types:
      - completed

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      ghcr-upload: ${{ steps.read-ci-config.outputs.ghcr-upload }}
      ghcr-cve-scan: ${{ steps.read-ci-config.outputs.ghcr-cve-scan }}
      build-matrix: ${{ steps.read-ci-config.outputs.build-matrix }}
      upload-matrix: ${{ steps.read-ci-config.outputs.upload-matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Read .github/ci.yaml
        id: read-ci-config
        uses: canonical/rocks-template-actions/actions/read-ci-config@v1   

  upload-ghcr:
    needs: [read-config]
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success' &&
      needs.read-config.outputs.ghcr-upload == 'true'
    strategy:
      matrix: ${{ fromJSON(needs.read-config.outputs.upload-matrix) }}
      fail-fast: false
    permissions:
      packages: write
    steps:
      - name: Upload Rock to GHCR
        if: ${{ github.event.repository.visibility != 'public' || !matrix.pro-enabled }}
        uses: canonical/oci-factory/.github/actions/upload-rock@main
        with:
          artifact_name: ${{ matrix.artifact-name }}
          tags: ${{ matrix.tag }}
          name: ${{ matrix.name }}
          registry: ghcr.io/${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

  upload-registries:
    needs: [read-config]
    if: |
      needs.read-config.outputs.upload-matrix != '{"include": []}'
    strategy:
      matrix: ${{ fromJSON(needs.read-config.outputs.upload-matrix) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Prepare ECR Session Token
        if: ${{ contains(matrix.registry-auth-method, 'ecr') }}
        id: get-ecr-token
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets[matrix.registry-auth-username] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets[matrix.registry-auth-password] }}
        run: |
          session_token=$(aws ${{ matrix.registry-auth-method }} \
                          get-login-password \
                          --region ${{ matrix.registry-auth-region }} \
                          )
          echo "::add-mask::$session_token"
          echo "aws-session-token=$session_token" >> $GITHUB_OUTPUT

      - name: Upload Rock to ECR
        uses: canonical/oci-factory/.github/actions/upload-rock@main
        if: ${{ contains(matrix.registry-auth-method, 'ecr') }}
        with:
          artifact_name: ${{ matrix.artifact-name }}
          tags: ${{ matrix.tag }}
          name: ${{ matrix.name }}
          registry: ${{ matrix.registry-uri }}
          username: AWS
          password: ${{ steps.get-ecr-token.outputs.aws-session-token }}

      - name: Upload Rock to Registry
        uses: canonical/oci-factory/.github/actions/upload-rock@main
        if: matrix.registry-auth-method == 'basic'
        with:
          artifact_name: ${{ matrix.artifact-name }}
          tags: ${{ matrix.tag }}
          name: ${{ matrix.name }}
          registry: ${{ matrix.registry-uri }}
          username: ${{ secrets[matrix.registry-auth-username] }}
          password: ${{ secrets[matrix.registry-auth-password] }}

